services:
  - type: web
    name: your-app-name
    env: static
    staticPublishPath: dist/spa
    buildCommand: quasar build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
